### ISSUE TITLE
Array to string notice on buildParameters()

### ISSUE THREAD

**Issue by bubach** [envms/fluentpdo#102]
I'm unsure if this is a false positive, perhaps I've made such heavy modification that I somehow cause this problem myself. Or perhaps I just have overly high error reporting on by default. Either way I can't get past the count() test loaclly, where the script will exit with an e_notice about "array to string conversion" on the SQL execute call.

Turns out that the fault can be traced to https://github.com/lichtner/fluentpdo/blob/master/FluentPDO/BaseQuery.php#L237 where an empty array gets added in the else-part.  I fixed this by changing the IF part to simply `if (is_array($value) ) {`.

I can not see how the other test would matter, as the parameter variable should never be more than one dimensional - right?

**Comment by cbornhoft** [comment]
When you say "count() test", do you mean [tests/59-countable.phpt](https://github.com/fpdo/fluentpdo/blob/master/tests/59-countable.phpt)?

All tests pass with the current build so I'm not sure where you mean it's failing.

**Comment by DurkStrooisma** [comment]
This issue still exists with normal code. I didn't check the tests.

For example:

```php
<?php

error_reporting(E_ALL);

require_once(dirname(__FILE__) . '/../lib/FluentPDO/FluentPDO.php');

$oConn = new PDO("mysql:host=localhost;dbname=central", 'central', 'central');
$oDb = new FluentPDO($oConn);

var_dump($oDb->from('`Sys`')
             ->select(null)
             ->select('`Name`')
             ->where('`Sys`.`Name` = ?', ['monitor', 'desktop'])
             ->fetchAll());
```

The problem is the array provide as possible values to match on, which, according to the documentation, is allowed. In the error log I'm getting:

`Notice:  Array to string conversion in BaseQuery.php on line 139`

Matching a single string value does work. And applying the fix by bubach make my example work. So I really wonder whether this indeed should be change in BaseQuery.php. I have patched this file myself now, but an upstream fix would be way better of course :-)

**Comment by cbornhoft** [comment]
Okay, we'll look into it again, thanks

**Comment by cbornhoft** [comment]
The solution to this is to remove the ` = ?` from the statement. Removing the extra cases from the if statement you both mentioned above will cause other problems with named parameters.

By writing:

    $fpdo->from('`system`')
             ->select(null)
             ->select('`name`')
             ->where('`system`.`name`', ['monitor', 'desktop'])
             ->fetchAll();

Everything works as expected, since the params are passed to the `addStatement()` method and handled within there, not upon execution.

**Comment by DurkStrooisma** [comment]
Thanks for the follow-up! That actually works. I'm happy that I can undo the hack.
