### ISSUE TITLE
Use PHP for joins instead of SQL

### ISSUE THREAD

**Issue by cbornhoft** [envms/fluentpdo#216]
Similar to [NotORM](http://www.notorm.com/)

This has several advantages, the biggest being performance.

**Comment by cbornhoft** [comment]
@carolyz @sanabria91 @maldoinc @jkufner @lichtner @StefanYohansson 

This is a big one, so let's start a discussion!

**Comment by jkufner** [comment]
Show us some examples of what you have on your mind.

**Comment by cbornhoft** [comment]
Have a look at http://www.notorm.com/#performance for a thorough example of exactly what I'm thinking.

If we can implement a way of maintaining the smart join features of Fluent, in addition to making SQL joins a thing of the past, that would be ideal.

A Fluent call like:

    $fpdo->from('article')
        ->select('user.name')
        ->where('user_id', 1)
        ->leftJoin('user ON user.id = article.user_id');

turns into two queries:

    SELECT user.name FROM user WHERE id = ?;
    SELECT * FROM article WHERE article.user_id = ?;

which are combined into 1 record set.

**Comment by jkufner** [comment]
It would be better to use NotORM directly. Such transformation of both SQL queries and PHP logic is far from trivial. Imagine you have 10 joins in the query. How do you split it?

I don't see a reason to reimplement it. It is not only about JOIN, it is also about foreign keys to make it work. However, NotORM looks a bit old and dusty, maybe it would be reasonable to port it into FluentPDO.

**Comment by maldoinc** [comment]
I think it's fine how it is and to be honest I'm not even sure if I like what that library is doing.

If performance is needed then it is probably better to just use a cache for the query generation part rather than reinventing joins.

**Comment by hapm** [comment]
Only to give another opinion: when I grasp the idea correctly, the only benefit is a reduced data transfer volume. Imho everything else stated as a benefit in this library hides the real problems. Databases are very good in evaluating an execution plan for joins based on the query. If a join performs bad, it is because of a bad query structure or bad table indices. Generating a fast execution plan is one of the main jobs a database should do. If you replace joins with PHP, you could also replace indexing with PHP, or why not simply replace the database by a file? Just kidding, but if I use a relational database as my backend I normally do that for a reason. If you replace one of the key features with some kind of simple PHP code, that is only performing good in some special cases, you should probably think about using another backend that better supports your use case.

**Comment by jkufner** [comment]
@hapm It is not about replacing joins. It is about effectively retrieving two related data sets. For example items and their labels, where each label may have many labels. JOIN is not a good way to do it for multiple reasons, e.g. it breaks LIMIT, GROUP BY, and other JOINs. Moreover, it is inefficient as you fetch the same item with each associated label.

Question is, whether is FluentPDO a query builder, or model layer. This feature is out of scope of a query builder, but it is useful feature of a model layer. In fact, I'm dealing with this feature too as I'm figuring out how to deal with relations in my [Smalldb](https://smalldb.org/) framework, and NotORM looks like a really good inspiration — thanks @cbornhoft for that, I completely forgot it exists.

**Comment by hapm** [comment]
@jkufner I never thought about FluentPDO being an ORM layer, therefor it is a query builder for me. If its goal is to be used as a model layer, operations like limit, group by and join sure have different meanings and should be implemented differently. If its goal is to be a query builder, what I thought it is, then this is out of scope as you already said.

**Comment by maldoinc** [comment]
I personally think this project should stick only to query building. The kind of problem that this proposes to solve is the "n+1 query" problem if I understand it correctly, and I would rather have the developer and the db engine deal with it.
