### ISSUE TITLE
Quick question about query building with arrays

### ISSUE THREAD

**Issue by mkddostro** [envms/fluentpdo#237]
Edit: sorry for the mess, I don't know how to line-break this lol

Based on the documentation/test files (where-array, where-column-array) I thought this would be possible (fixed test values):

`$where = array();
$where['user_id'] = $user['id'];
$where['project_id'] = array(1,3,7);
$where['priority'] = array(1,3);
$where['(completed_at = ? OR started_at = ?)'] = array('0000-00-00 00:00:00', '0000-00-00 00:00:00');
$testquery = $fluent_lvs->from('task')->where($where);`

The query, actually, is being built as
`SELECT task.*
FROM task
WHERE user_id = ?
    AND project_id IN (1, 3, 7)
    AND priority IN (1, 3)
    AND (completed_at = ? OR started_at = ?)`
which I expected but it doesn't work (returns false and goes into debugging). I've changed the debugging a bit to get access to thrown errors and I got "HY093" for invalid parameter number but I don't see how it's invalid.

What am I missing? Is this even possible in any way?

**Comment by cbornhoft** [comment]
Apologies for the late response, I've been away. Hmm, I haven't seen where clauses being built out like this before, but it looks like everything is correct, _except_ for the last clause. You've got 1 condition and 2 parameters.

`(completed_at = ? OR started_at = ?)` acts like one condition. I know that you're trying to use OR, which is why you wrote it in that form. However, it won't work.

**Comment by mkddostro** [comment]
No worries, thanks for explaining.
I saw a comment on here somewhere about how this would make OR statements possible but it was "just another user" so probably wrong.
